// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using YongzCreative.Models;

namespace YongzCreative.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20200521095528_InitiateData")]
    partial class InitiateData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("YongzCreative.Models.CartLine", b =>
                {
                    b.Property<int>("CartLineID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("OrderID");

                    b.Property<int?>("ProductId");

                    b.Property<int>("Quantity");

                    b.HasKey("CartLineID");

                    b.HasIndex("OrderID");

                    b.HasIndex("ProductId");

                    b.ToTable("CartLine");
                });

            modelBuilder.Entity("YongzCreative.Models.Category", b =>
                {
                    b.Property<int>("CategoryID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CategoryName")
                        .IsRequired();

                    b.HasKey("CategoryID");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryID = 1,
                            CategoryName = "Cap"
                        },
                        new
                        {
                            CategoryID = 2,
                            CategoryName = "Hoodie"
                        },
                        new
                        {
                            CategoryID = 3,
                            CategoryName = "Sweater"
                        },
                        new
                        {
                            CategoryID = 4,
                            CategoryName = "T Shirt"
                        },
                        new
                        {
                            CategoryID = 5,
                            CategoryName = "Sweatpants"
                        },
                        new
                        {
                            CategoryID = 6,
                            CategoryName = "Leggings"
                        });
                });

            modelBuilder.Entity("YongzCreative.Models.Order", b =>
                {
                    b.Property<int>("OrderID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("City")
                        .IsRequired();

                    b.Property<string>("Line1")
                        .IsRequired();

                    b.Property<string>("Line2");

                    b.Property<string>("Line3");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<bool>("Shipped");

                    b.Property<string>("Zip");

                    b.HasKey("OrderID");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("YongzCreative.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CategoryID");

                    b.Property<string>("Description");

                    b.Property<string>("ImagePath");

                    b.Property<string>("Name");

                    b.Property<decimal>("Price");

                    b.Property<int>("status");

                    b.HasKey("ProductId");

                    b.HasIndex("CategoryID");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            CategoryID = 2,
                            Description = "A hoodie to rock your body.",
                            ImagePath = "/images/hoodies/Hoodie01.png",
                            Name = "Blue Hoodie",
                            Price = 350m,
                            status = 0
                        },
                        new
                        {
                            ProductId = 2,
                            CategoryID = 2,
                            Description = "",
                            ImagePath = "/images/hoodies/Hoodie02.png",
                            Name = "Orange Hoodie",
                            Price = 350m,
                            status = 1
                        },
                        new
                        {
                            ProductId = 3,
                            CategoryID = 2,
                            Description = "A splashed hoodie that adds taste to your body.",
                            ImagePath = "/images/hoodies/Hoodie03.png",
                            Name = "Black Hoodie",
                            Price = 350m,
                            status = 0
                        },
                        new
                        {
                            ProductId = 4,
                            CategoryID = 2,
                            Description = "Black and yellow kinda taste.",
                            ImagePath = "/images/hoodies/Hoodie00.png",
                            Name = "Black Hoodie",
                            Price = 350m,
                            status = 1
                        },
                        new
                        {
                            ProductId = 5,
                            CategoryID = 2,
                            Description = "",
                            ImagePath = "/images/hoodies/Hoodie04.png",
                            Name = "Black Hoodie",
                            Price = 350m,
                            status = 0
                        },
                        new
                        {
                            ProductId = 6,
                            CategoryID = 2,
                            Description = "",
                            ImagePath = "/images/hoodies/Hoodie05.png",
                            Name = "Grey and Blue Hoodie",
                            Price = 350m,
                            status = 1
                        },
                        new
                        {
                            ProductId = 7,
                            CategoryID = 1,
                            Description = "Meroon Cap",
                            ImagePath = "/images/caps/cap04.png",
                            Name = "YONGZ Cap",
                            Price = 130m,
                            status = 0
                        },
                        new
                        {
                            ProductId = 8,
                            CategoryID = 1,
                            Description = "Black Cap",
                            ImagePath = "/images/caps/cap03.png",
                            Name = "YONGZ Cap",
                            Price = 130m,
                            status = 0
                        },
                        new
                        {
                            ProductId = 9,
                            CategoryID = 1,
                            Description = "Pitch Cap",
                            ImagePath = "/images/caps/cap02.png",
                            Name = "YONGZ Cap",
                            Price = 130m,
                            status = 0
                        },
                        new
                        {
                            ProductId = 10,
                            CategoryID = 1,
                            Description = "Green Cap",
                            ImagePath = "/images/caps/cap01.png",
                            Name = "BAD ART CAP",
                            Price = 130m,
                            status = 1
                        },
                        new
                        {
                            ProductId = 11,
                            CategoryID = 1,
                            Description = "Yellow Cap",
                            ImagePath = "/images/caps/cap05.png",
                            Name = "BAD ART CAP",
                            Price = 130m,
                            status = 1
                        },
                        new
                        {
                            ProductId = 12,
                            CategoryID = 3,
                            Description = "",
                            ImagePath = "/images/sweaters/sweater00.png",
                            Name = "Sky Blue Sweater",
                            Price = 350m,
                            status = 1
                        },
                        new
                        {
                            ProductId = 13,
                            CategoryID = 3,
                            Description = "",
                            ImagePath = "/images/sweaters/sweater01.png",
                            Name = "Black Sweater",
                            Price = 350m,
                            status = 0
                        },
                        new
                        {
                            ProductId = 14,
                            CategoryID = 3,
                            Description = "",
                            ImagePath = "/images/sweaters/sweater02.png",
                            Name = "Orange Sweater",
                            Price = 350m,
                            status = 0
                        },
                        new
                        {
                            ProductId = 15,
                            CategoryID = 3,
                            Description = "",
                            ImagePath = "/images/sweaters/sweater03.png",
                            Name = "Blue Sweater",
                            Price = 350m,
                            status = 1
                        },
                        new
                        {
                            ProductId = 16,
                            CategoryID = 3,
                            Description = "",
                            ImagePath = "/images/sweaters/sweater04.png",
                            Name = "Yellow Sweater",
                            Price = 350m,
                            status = 1
                        },
                        new
                        {
                            ProductId = 17,
                            CategoryID = 3,
                            Description = "",
                            ImagePath = "/images/sweaters/sweater05.png",
                            Name = "3 Coloured Sweater",
                            Price = 350m,
                            status = 1
                        },
                        new
                        {
                            ProductId = 18,
                            CategoryID = 6,
                            Description = "",
                            ImagePath = "/images/leggings/leggings00.png",
                            Name = "Black Leggings",
                            Price = 180m,
                            status = 0
                        },
                        new
                        {
                            ProductId = 19,
                            CategoryID = 6,
                            Description = "",
                            ImagePath = "/images/leggings/leggings01.png",
                            Name = "Grey Leggings",
                            Price = 180m,
                            status = 0
                        },
                        new
                        {
                            ProductId = 20,
                            CategoryID = 6,
                            Description = "with white stripes",
                            ImagePath = "/images/leggings/leggings02.png",
                            Name = "Black Leggings",
                            Price = 180m,
                            status = 0
                        },
                        new
                        {
                            ProductId = 21,
                            CategoryID = 6,
                            Description = "",
                            ImagePath = "/images/leggings/leggings03.png",
                            Name = "Black Leggings",
                            Price = 180m,
                            status = 0
                        },
                        new
                        {
                            ProductId = 22,
                            CategoryID = 6,
                            Description = "",
                            ImagePath = "/images/leggings/leggings04.png",
                            Name = "Pink Leggings",
                            Price = 180m,
                            status = 1
                        },
                        new
                        {
                            ProductId = 23,
                            CategoryID = 6,
                            Description = "",
                            ImagePath = "/images/leggings/leggings05.png",
                            Name = "Navy Blue Leggings",
                            Price = 180m,
                            status = 1
                        },
                        new
                        {
                            ProductId = 24,
                            CategoryID = 6,
                            Description = "",
                            ImagePath = "/images/leggings/leggings06.png",
                            Name = "Grey Leggings",
                            Price = 180m,
                            status = 1
                        },
                        new
                        {
                            ProductId = 25,
                            CategoryID = 6,
                            Description = "",
                            ImagePath = "/images/leggings/leggings07.png",
                            Name = "Dark Blue Leggings",
                            Price = 180m,
                            status = 1
                        },
                        new
                        {
                            ProductId = 26,
                            CategoryID = 6,
                            Description = "",
                            ImagePath = "/images/leggings/leggings08.png",
                            Name = "Double Grey Leggings",
                            Price = 180m,
                            status = 1
                        },
                        new
                        {
                            ProductId = 27,
                            CategoryID = 6,
                            Description = "",
                            ImagePath = "/images/leggings/leggings09.png",
                            Name = "Blue and Black Leggings",
                            Price = 180m,
                            status = 1
                        },
                        new
                        {
                            ProductId = 28,
                            CategoryID = 6,
                            Description = "",
                            ImagePath = "/images/leggings/leggings10.png",
                            Name = "Black Leggings",
                            Price = 180m,
                            status = 1
                        },
                        new
                        {
                            ProductId = 29,
                            CategoryID = 4,
                            Description = "A collection of BAD ARD T-Shirts at only R200 each",
                            ImagePath = "/images/tshirts/_0000_Tshirt.jpg",
                            Name = "T-Shirts",
                            Price = 200m,
                            status = 0
                        },
                        new
                        {
                            ProductId = 30,
                            CategoryID = 4,
                            Description = "",
                            ImagePath = "/images/tshirts/_0001_Tshirt.jpg",
                            Name = "White Top",
                            Price = 200m,
                            status = 0
                        },
                        new
                        {
                            ProductId = 31,
                            CategoryID = 4,
                            Description = "Black",
                            ImagePath = "/images/tshirts/_0002_Tshirt.jpg",
                            Name = "YONGZ Top",
                            Price = 200m,
                            status = 0
                        },
                        new
                        {
                            ProductId = 32,
                            CategoryID = 4,
                            Description = "White",
                            ImagePath = "/images/tshirts/_0003_Tshirt.jpg",
                            Name = "YONGZ Top",
                            Price = 200m,
                            status = 0
                        },
                        new
                        {
                            ProductId = 33,
                            CategoryID = 4,
                            Description = "Pitch",
                            ImagePath = "/images/tshirts/_0004_Tshirt.jpg",
                            Name = "YONGZ Top",
                            Price = 200m,
                            status = 0
                        },
                        new
                        {
                            ProductId = 34,
                            CategoryID = 4,
                            Description = "BAD ART Stickman",
                            ImagePath = "/images/tshirts/_0005_Tshirt.jpg",
                            Name = "White Top",
                            Price = 200m,
                            status = 0
                        },
                        new
                        {
                            ProductId = 35,
                            CategoryID = 5,
                            Description = "",
                            ImagePath = "/images/sweatpants/Sweatpants00.png",
                            Name = "Grey Sweatpants",
                            Price = 300m,
                            status = 1
                        },
                        new
                        {
                            ProductId = 36,
                            CategoryID = 5,
                            Description = "",
                            ImagePath = "/images/sweatpants/Sweatpants01.png",
                            Name = "Red Sweatpants",
                            Price = 300m,
                            status = 0
                        },
                        new
                        {
                            ProductId = 37,
                            CategoryID = 5,
                            Description = "",
                            ImagePath = "/images/sweatpants/Sweatpants02.png",
                            Name = "Yellow Sweatpants",
                            Price = 300m,
                            status = 1
                        },
                        new
                        {
                            ProductId = 38,
                            CategoryID = 5,
                            Description = "",
                            ImagePath = "/images/sweatpants/Sweatpants03.png",
                            Name = "Grey Sweatpants",
                            Price = 300m,
                            status = 1
                        });
                });

            modelBuilder.Entity("YongzCreative.Models.CartLine", b =>
                {
                    b.HasOne("YongzCreative.Models.Order")
                        .WithMany("Lines")
                        .HasForeignKey("OrderID");

                    b.HasOne("YongzCreative.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId");
                });

            modelBuilder.Entity("YongzCreative.Models.Product", b =>
                {
                    b.HasOne("YongzCreative.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryID")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
