// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using YongzCreative.Models;

namespace YongzCreative.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20200423224159_NewHoodiesAndCaps")]
    partial class NewHoodiesAndCaps
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("YongzCreative.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description");

                    b.Property<string>("ImagePath");

                    b.Property<string>("Name");

                    b.Property<decimal>("Price");

                    b.Property<int>("category");

                    b.Property<int>("status");

                    b.HasKey("ProductId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            Description = "A hoodie to rock your body.",
                            ImagePath = "/images/hoodies/Hoodie01.png",
                            Name = "Blue Hoodie",
                            Price = 350m,
                            category = 1,
                            status = 0
                        },
                        new
                        {
                            ProductId = 2,
                            Description = "",
                            ImagePath = "/images/hoodies/Hoodie02.png",
                            Name = "Orange Hoodie",
                            Price = 350m,
                            category = 1,
                            status = 1
                        },
                        new
                        {
                            ProductId = 3,
                            Description = "A splashed hoodie that adds taste to your body.",
                            ImagePath = "/images/hoodies/Hoodie03.png",
                            Name = "Black Hoodie",
                            Price = 350m,
                            category = 1,
                            status = 0
                        },
                        new
                        {
                            ProductId = 4,
                            Description = "Black and yellow kinda taste.",
                            ImagePath = "/images/hoodies/Hoodie00.png",
                            Name = "Black Hoodie",
                            Price = 350m,
                            category = 1,
                            status = 1
                        },
                        new
                        {
                            ProductId = 5,
                            Description = "",
                            ImagePath = "/images/hoodies/Hoodie04.png",
                            Name = "Black Hoodie",
                            Price = 350m,
                            category = 1,
                            status = 0
                        },
                        new
                        {
                            ProductId = 6,
                            Description = "",
                            ImagePath = "/images/hoodies/Hoodie05.png",
                            Name = "Grey and Blue Hoodie",
                            Price = 350m,
                            category = 1,
                            status = 1
                        },
                        new
                        {
                            ProductId = 7,
                            Description = "Meroon Cap",
                            ImagePath = "/images/caps/cap04.png",
                            Name = "YONGZ Cap",
                            Price = 130m,
                            category = 0,
                            status = 0
                        },
                        new
                        {
                            ProductId = 8,
                            Description = "Black Cap",
                            ImagePath = "/images/caps/cap03.png",
                            Name = "YONGZ Cap",
                            Price = 130m,
                            category = 0,
                            status = 0
                        },
                        new
                        {
                            ProductId = 9,
                            Description = "Pitch Cap",
                            ImagePath = "/images/caps/cap02.png",
                            Name = "YONGZ Cap",
                            Price = 130m,
                            category = 0,
                            status = 0
                        },
                        new
                        {
                            ProductId = 10,
                            Description = "Green Cap",
                            ImagePath = "/images/caps/cap01.png",
                            Name = "BAD ART CAP",
                            Price = 130m,
                            category = 0,
                            status = 1
                        },
                        new
                        {
                            ProductId = 11,
                            Description = "Yellow Cap",
                            ImagePath = "/images/caps/cap05.png",
                            Name = "BAD ART CAP",
                            Price = 130m,
                            category = 0,
                            status = 1
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
