// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using YongzCreative.Models;

namespace YongzCreative.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20200211214032_InitialData")]
    partial class InitialData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.0-rtm-35687")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("YongzCreative.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description");

                    b.Property<string>("ImagePath");

                    b.Property<string>("Name");

                    b.Property<decimal>("Price");

                    b.HasKey("ProductId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            Description = "Black cap with a taste of red.",
                            ImagePath = "~\\images\\Cap01.png",
                            Name = "YONGZ Cap",
                            Price = 275m
                        },
                        new
                        {
                            ProductId = 2,
                            Description = "Peach cap styled with maroon.",
                            ImagePath = "~\\images\\Cap02.png",
                            Name = "YONGZ Cap",
                            Price = 1200m
                        },
                        new
                        {
                            ProductId = 3,
                            Description = "Black cap lightened up with white.",
                            ImagePath = "~\\images\\Cap03.png",
                            Name = "YONGZ Cap",
                            Price = 1200m
                        },
                        new
                        {
                            ProductId = 4,
                            Description = "Maroon cap styled with white.",
                            ImagePath = "~\\images\\Cap04.png",
                            Name = "YONGZ Cap",
                            Price = 1200m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
